# GET http://localhost:3000/api/users


# POST http://localhost:3000/api/users
# Content-Type: application/json

# {
#   "name": "Joshua",
#   "email": "Joshua@email.com"
# }

PUT http://localhost:3000/api/users/2
Content-Type: application/json

{
  "name": "Sam",
  "email": "Samantha@email.com"
}

# PUT http://localhost:3000/api/users/3
# Content-Type: application/json

# {
#   "name": "Josh",
#   "email": "Joshua@email.com"
# }