# POST http://localhost:3000/api/users
# Content-Type: application/json


# { 
#   "name": "Joshua",
#   "email": "joshua@email.com"
# }

# PUT http://localhost:3000/api/users/3
# Content-Type: application/json


# { 
#   "name": "Joshua",
#   "email": "joshua@email.com"
# }

DELETE http://localhost:3000/api/users/3
